---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # The name of the StorageClass.
  name: sc.azurelustre.csi.azure.com
parameters:
  # The IP address of the existing Lustre
  mgs-ip-address: ${EXISTING_LUSTRE_IP_ADDRESS}
provisioner: azurelustre.csi.azure.com
# Azure Lustre Cluster is removed after PVC deletion if reclaimPolicy is the default value "Delete".
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - noatime
  - flock
