apiVersion: v1
entries:
  azurelustre-csi-driver:
  - apiVersion: v2
    appVersion: latest
    created: "2026-07-29T12:18:49.201089353-04:00"
    description: Azure Lustre CSI Driver Helm chart
    digest: df358fc470f9e15c65788e5dd7cc86651075265e1fe12c37206f54928d16fabf
    home: https://github.com/kubernetes-sigs/azurelustre-csi-driver
    keywords:
    - storage
    - csi
    - azure
    - lustre
    kubeVersion: '>=1.29.0-0'
    name: azurelustre-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/azurelustre-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurelustre-csi-driver/main/charts/latest/azurelustre-csi-driver-v0.0.0.tgz
    version: v0.0.0
generated: "2026-07-29T12:18:49.19992035-04:00"
